const data = {
  DataBase: {
    Pets: [
      {
        id: 1,
        type: "cat",
        name: "Tom",
        age: "4 Months",
        pic: "../assets/PitPic/cat.jpg",
        color: "black",
        weight: 2,
        food_Time: { breakfast: "", diner: "", lanche: "" },
        contact: "",
      },
      {
        id: 2,
        type: "dog",
        name: "jon",
        age: "2 Years",
        pic: "../assets/PitPic/dog.jpg",
        color: "white",
        weight: 2,
        food_Time: { breakfast: "", diner: "", lanche: "" },
        contact: "",
      },
      {
        id: 3,
        type: "rabbit",
        name: "omnya",
        age: "1 Year",
        pic: "../assets/PitPic/rabbit.jpg",
        color: "black",
        weight: 2,
        food_Time: { breakfast: "", diner: "", lanche: "" },
        contact: "",
      },
      {
        id: 4,
        type: "bird",
        name: "sa3id",
        age: "7 Months",
        pic: "../assets/PitPic/bird.jpg",
        color: "black",
        weight: 2,
        food_Time: { breakfast: "", diner: "", lanche: "" },
        contact: "",
      },
    ],
    Adopt_Pet: [],
    Veterinarians: [
      {
        id: 1,
        f_name: "Aymane",
        l_name: "harchi",
        pic: "../assets/VetPic/vetMen.jpg",
        email: "Aymane@gmail.com",
        phone: "617663421",
      },
      {
        id: 2,
        f_name: "Soufian",
        l_name: "ounjli",
        pic: "../assets/VetPic/vetMen.jpg",
        email: "Soufian@gmail.com",
        phone: "786519871",
      },
      {
        id: 3,
        f_name: "Yassin",
        l_name: "man3reft",
        pic: "../assets/VetPic/vetMen.jpg",
        email: "Yassin@gmail.com",
        phone: "733451879",
      },
      {
        id: 4,
        f_name: "Mohemmed",
        l_name: "Abdellaoui",
        pic: "../assets/VetPic/vetMen.jpg",
        email: "Mohammed@gmail.com",
        phone: "613946107",
      },
    ],
    Pet_Food: [
      {
        type: "bird",
        food_title: "Crecket for cut",
        food_pic: "",
        food_price: "20dh",
        food_weight: "1kg",
      },
    ],
    Cart: [],
    Favourite: [],
  },
};
export default data;
