const data = {
  DataBase: {
    Pets: [
      {
        id: 1,
        type: "cat",
        name: "Tom",
        age: "4 Months",
        price:"120dh",
        pic: "../assets/PitPic/cat.jpg",
        color: "black",
        weight: 2,
        // food_Time: { breakfast: "", diner: "", lanche: "" },
        contact: "",
        Adopted_date:""
      },
      {
        id: 2,
        type: "dog",
        name: "jon",
        age: "2 Years",
        price:"300dh",
        pic: "../assets/PitPic/beautiful-pet-portrait-dog.jpg",
        color: "white",
        weight: 2,
        // food_Time: { breakfast: "", diner: "", lanche: "" },
        contact: "",
        Adopted_date:""
      },
      {
        id: 3,
        type: "rabbit",
        name: "omnya",
        age: "1 Year",
        price:"155dh",
        pic: "../assets/PitPic/rabbit.jpg",
        color: "black",
        weight: 2,
        // food_Time: { breakfast: "", diner: "", lanche: "" },
        contact: "",
        Adopted_date:""
      },
      {
        id: 4,
        type: "bird",
        name: "sa3id",
        age: "7 Months",
        price:"210dh",
        pic: "../assets/PitPic/bird.jpg",
        color: "black",
        weight: 2,
        // food_Time: { breakfast: "", diner: "", lanche: "" },
        contact: "",
        Adopted_date:""
      },
    ],
    Adopt_Pet: [],
    Veterinarians: [
      {
        id: 1,
        f_name: "Aymane",
        l_name: "fri7a",
        pic: "../assets/VetPic/vetMen.jpg",
        email: "Aymane@gmail.com",
        phone: "617663421",
      },
      {
        id: 2,
        f_name: "Soufian",
        l_name: "l3alawi",
        pic: "../assets/VetPic/vetMen.jpg",
        email: "Soufian@gmail.com",
        phone: "786519871",
      },
      {
        id: 3,
        f_name: "Yassin",
        l_name: "znide9",
        pic: "../assets/VetPic/vetMen.jpg",
        email: "Yassin@gmail.com",
        phone: "733451879",
      },
      {
        id: 4,
        f_name: "Mohammed",
        l_name: "fertut",
        pic: "../assets/VetPic/vetMen.jpg",
        email: "Mohammed@gmail.com",
        phone: "613946107",
      },
    ],
    Pet_Food: [
      {
        type: "cat",
        food_title: "Crecket for cats",
        food_pic: "../assets/FoodPic/food3.png",
        food_price: "20dh",
        food_weight: "1kg",
      },
      {
        type: "cat",
        food_title: "Crecket for cats",
        food_pic: "../assets/FoodPic/food4.jpg",
        food_price: "20dh",
        food_weight: "1kg",
      },
      {
        type: "bird",
        food_title: "food for bird ",
        food_pic: "../assets/FoodPic/food2.jpg",
        food_price: "10dh",
        food_weight: "1kg",
      },
      {
        type: "bird",
        food_title: "premium seeds mix",
        food_pic: "../assets/FoodPic/food3.png",
        food_price: "15dh",
        food_weight: "1.5kg",
      },
      {
        type: "bird",
        food_title: "organic bird pellets",
        food_pic: "../assets/FoodPic/food4.jpg",
        food_price: "12dh",
        food_weight: "1.2kg",
      },
      {
        type: "dog",
        food_title: "Checken for dogs",
        food_pic: "../assets/FoodPic/food1.jpg",
        food_price: "30dh",
        food_weight: "1kg",
      },
      {
        type: "dog",
        food_title: "chicken flavor kibble",
        food_pic: "../assets/FoodPic/food1.jpg",
        food_price: "25dh",
        food_weight: "2kg",
      },
      {
        type: "dog",
        food_title: "beef and rice",
        food_pic: "../assets/FoodPic/food1.jpg",
        food_price: "30dh",
        food_weight: "3kg",
      },   
      {
        type: "dog",
        food_title: "lamb and vegetable",
        food_pic: "../assets/FoodPic/food1.jpg",
        food_price: "35dh",
        food_weight: "2.5kg",
      },
      {
        type: "rabbit",
        food_title: "Crecket for rabbit",
        food_pic: "../assets/FoodPic/food4.jpg",
        food_price: "15dh",
        food_weight: "1kg",
      },
    ],
    Cart: [],
    Favourite: [],
  },
};
export default data;
